services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=smart-bank'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:7'
    ports:
      - '6379:6379'
